### ISSUE TITLE
[Bug]: Ryujinx: Could not fetch local mods

### ISSUE THREAD

**Issue by vatstav** [vasilvestre/totk-mod-manager-for-switch-emulators#39]
### Describe the bug

```bash
When i select the option for ryujinx the app shows that message "Could not fetch local mods"
...
```

### Reproduction steps

```bash
1.open app
2.select ryujinx
...
```

### Additional context

```bash
...
```

### What's your operating system?

Windows 10

**Comment by vasilvestre** [comment]
Can you test 0.9.3 and confirm the behaviour ?

**Comment by vatstav** [comment]
working perfectly on 0.9.4

**Comment by vasilvestre** [comment]
Old config issues, this is now fixed. Sorry for inconvenience, enjoy !
