### ISSUE TITLE
[Bug]: defaulting to yuzu as i select the ryujinx option

### ISSUE THREAD

**Issue by SayianRonin1996** [vasilvestre/totk-mod-manager-for-switch-emulators#40]
### Describe the bug

```bash
1.when i open up the launcher and click on ryujinx it defaults to Yuzu
2. not giving the option to return and select ryujinx
3. constantly seeing the error '1.find is not a feature'
```

### Reproduction steps

```bash
1.click on the ryujinx option and thats about it
```

### What's your operating system?

Windows 11

**Comment by vasilvestre** [comment]
Please try the newest 0.9.*, mau y have fixed the issue

**Comment by SayianRonin1996** [comment]
it opens up the ryujin option but it says path not allowed within the configured scope. im not sure whats going wrong with that but hopefully its resolved in the next update

**Comment by vasilvestre** [comment]
> it opens up the ryujin option but it says path not allowed within the configured scope. im not sure whats going wrong with that but hopefully its resolved in the next update

I have an idea about why this happens, can you share your ryujinx path please ?

**Comment by SayianRonin1996** [comment]
its installed directly on my ssd
D:\Ryujinx

**Comment by SayianRonin1996** [comment]
the mod folder however C:\Users\\AppData\Roaming\Ryujinx\mods\contents\0100F2C0115B6000

**Comment by vasilvestre** [comment]
> the mod folder however C:\Users\AppData\Roaming\Ryujinx\mods\contents\0100F2C0115B6000

I didn't knew you could do that, it's definitly the issue here. I will have to change a bit the configuration and way the app works

**Comment by vasilvestre** [comment]
> 

Can you choose C:\Users\AppData\Roaming\Ryujinx\ folder when asked for it please ? I think the readme isn't good enough

**Comment by SayianRonin1996** [comment]
> > 
> 
> Can you choose C:\Users\AppData\Roaming\Ryujinx\ folder when asked for it please ? I think the readme isn't good enough

the mod manager isn't asking me for the ryujinx user directory or giviung me an option to select it. I can record my screen so you can see the exact issue if you want

**Comment by vasilvestre** [comment]
> > > 
> > 
> > Can you choose C:\Users\AppData\Roaming\Ryujinx\ folder when asked for it please ? I think the readme isn't good enough
> 
> the mod manager isn't asking me for the ryujinx user directory or giviung me an option to select it. I can record my screen so you can see the exact issue if you want

Sure ! Update to last version first please :)

**Comment by SayianRonin1996** [comment]
> > > > 
> > > 
> > > 
> > > Can you choose C:\Users\AppData\Roaming\Ryujinx\ folder when asked for it please ? I think the readme isn't good enough
> > 
> > 
> > the mod manager isn't asking me for the ryujinx user directory or giviung me an option to select it. I can record my screen so you can see the exact issue if you want
> 
> Sure ! Update to last version first please :)

the mod manager is all up to date and heres a recording of my issue https://youtu.be/kMT2X5gPU4k

**Comment by vasilvestre** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Can you choose C:\Users\AppData\Roaming\Ryujinx\ folder when asked for it please ? I think the readme isn't good enough
> > > 
> > > 
> > > the mod manager isn't asking me for the ryujinx user directory or giviung me an option to select it. I can record my screen so you can see the exact issue if you want
> > 
> > 
> > Sure ! Update to last version first please :)
> 
> the mod manager is all up to date and heres a recording of my issue https://youtu.be/kMT2X5gPU4k

The issue seems to have changed, it doesn't open to Yuzu anymore so ?

See https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/issues/45#issuecomment-1574762058 to continue please :)

**Comment by SayianRonin1996** [comment]
I can still open up the yuzu option fine iit's just not giving me a prompt
to select my ryujinx path so it can detect the issue. If there's any new
updates I'll have to wait 8 hours to check as I'm at my workplace at the
moment
