### ISSUE TITLE
[Bug]: App won't detect local mods regardless of which Yuzu folder I choose

### ISSUE THREAD

**Issue by durrburger93** [vasilvestre/totk-mod-manager-for-switch-emulators#43]
### Describe the bug

```bash
1.I tried finding both the Roaming/yuzu folder and the actual exe folder, none of them work in the mod.
2. Regardless of the patch, I'm getting the could not fetch local mods error
...
```

### Reproduction steps

```bash
1. open app
2. select yuzu
3. manually select the folder
...
```

### Additional context

```bash
1.
2.
3.
...
```

### What's your operating system?

Windows 11

**Comment by Mieskoh** [comment]
I have a similar bug, but I can add that after clearing the cache, the error changes to "path not allowed on the configured scope", before going back to the could not fetch mods error again. I also tried the other debug option, and that one does nothing.

**Comment by vasilvestre** [comment]
> I have a similar bug, but I can add that after clearing the cache, the error changes to "path not allowed on the configured scope", before going back to the could not fetch mods error again. I also tried the other debug option, and that one does nothing.
> 
> My version of the app is the latest one, 0.9.6.
> 
> I don't know if it's related or not, but might as well point out that the version on banana is still the 0.5, but the built in update did not work either, it launched a console, restarted the app, only to ask me if I wanted to install the update again.

Can you share your path that's not allowed on the configured scope please ?
This is a known bug that I can't replicate while I don't have a windows

**Comment by Mieskoh** [comment]
The path is "G:\Games\Yuzu EA"

**Comment by vasilvestre** [comment]
> The path is "G:\Games\Yuzu EA"

So normally, when you launch the app and choose Yuzu, the app ask you for Yuzu path that's right ?

**Comment by Mieskoh** [comment]
I have to click the text asking for the path after choosing yuzu, but I noticed that it gives me the could not fetch error before I do.

**Comment by vasilvestre** [comment]
> 

Ok maybe I have a workflow issue here but you still can choose a directory ? The directory to select is the Yuzu folder that contains a directory "Mod"

**Comment by Mieskoh** [comment]
I can, but it doesn't work nonetheless, I also tried to put the .exe inside the same folder.

**Comment by vasilvestre** [comment]
> I can, but it doesn't work nonetheless, I also tried to put the .exe inside the same folder.

I will try to reproduce this in 2 days when I have a windows

**Comment by Mieskoh** [comment]
Ok, I hope you'll find a fix :)

**Comment by Mieskoh** [comment]
Quick update: I tried the new release, still not working, and now the text to choose the folder is gone.

**Comment by vasilvestre** [comment]
> Quick update: I tried the new release, still not working, and now the text to choose the folder is gone.

Yes, please use the debug button to remove your configuration. The new system isn't compatible with the previous one for a file :)

**Comment by Mieskoh** [comment]
That fixed that issue, but the underlying one is still there, I hope you'll find something!

**Comment by vasilvestre** [comment]
https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/issues/49#issuecomment-1584359228

I've sent a video, the other issue is quite similar to this one. You are doing to same things?

**Comment by Mieskoh** [comment]
So, I started spamming the two buttons, and at some point it started working, for some reason lol, thanks!

**Comment by vasilvestre** [comment]
Nice ! I've discovered a new way to handle the configuration still, this will make the whole app more stable. I keep learning :) Happy that it works !

**Comment by vasilvestre** [comment]
@durrburger93 feel free to reopen
