### ISSUE TITLE
[Bug] "path not allowed on the configured scope: C:\\Users\\((UserName))\\AppData\\Roaming\\Ryujinx"

### ISSUE THREAD

**Issue by Deeves** [vasilvestre/totk-mod-manager-for-switch-emulators#45]
Describe the bug
When I select the option for ryujinx the app shows a message in the corner "path not allowed on the configured scope: C:\\Users\\((UserName))\\AppData\\Roaming\\Ryujinx"
...
Reproduction steps
1.open app
2.select ryujinx
...
Additional context
I attempted to install using both regular .exe and .msi files, as well as the portable version. I also attempted to place the portable version directly into the roaming folder and ran all versions with administrative privileges. However, none of these methods were successful.
...
What's your operating system?
Windows 10
![Screenshot 2023-06-02 153550](https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/assets/4407588/0170afa1-c41e-4ab4-94e7-3aa60f70dee2)

**Comment by mgreed** [comment]
+1, same error, same path, win10

**Comment by NeuroticNinjah** [comment]
Did you guys do the steps in the big report? That has been helping some people so might be worth a try.

**Comment by mgreed** [comment]
> Did you guys do the steps in the bug report? That has been helping some people so might be worth a try.

If you're talking about the CLEAR INNER CACHE and CLEAR CONFIG FILE options, yeah I tried those. No luck.

**Comment by vasilvestre** [comment]
I think Linux and Windows behavior is different toward configured scope, I just made a fix release. Feel free to try 0.9.4 and tell me if things get better

**Comment by mgreed** [comment]
> I think Linux and Windows behavior is different toward configured scope, I just made a fix release. Feel free to try 0.9.4 and tell me if things get better
> 
> https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/releases/tag/v0.9.4

Looking good here, that did it for me. Thank you!

**Comment by vasilvestre** [comment]
Feel free to reopen
