### ISSUE TITLE
[Bug]: OpenSSL 1.1 is reaching its end of life on 2023/09/11

### ISSUE THREAD

**Issue by Krutonium** [vasilvestre/totk-mod-manager-for-switch-emulators#46]
### Describe the bug

```bash
1. Your mod manager is using OpenSSL 1.1
2. My Distro will stop supporting it/allowing it to be installed when that happens
3. You should probably set yourself up to use a newer version
```
https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
### What's your operating system?

Linux

**Comment by vasilvestre** [comment]
Please see the guide, afaik tauri have no solution except install the ssl for now :( sorry this isn't secure but it's not a priority right now. AppImage works nice

**Comment by vasilvestre** [comment]
See https://github.com/tauri-apps/tauri/issues/4470
