### ISSUE TITLE
This triggered a virus warning!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [vasilvestre/totk-mod-manager-for-switch-emulators#51]
![seccenter_imuualCQXR 1](https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/assets/10351221/b8091c69-4da4-4320-b814-3b5142c0665e)

**Comment by vasilvestre** [comment]
Being ""secure"" cost 100-200$ to buy a license, it's not even sure you will be ""secure"".
That's a false positive here, I've submitted the exe to Microsoft but yeah, I should contact bitdefender too. Thanks for the report

**Comment by vasilvestre** [comment]
> I know it might be because I don't see you having malicious intent but it is the age of bad actors and I am not alone when I say - better safe than sorry.

Sure I understand. I myself took an interest to the dependencies of the project because I know my code is medium but not malicious. Turns out software require to pay to be seen safe, the web is way more dangerous. I understand you and it's fine :) happy modding

**Comment by vasilvestre** [comment]
See https://github.com/vasilvestre/totk-mod-manager-for-switch-emulators/issues/53 for more details, virustotal will now be run at release.
