### ISSUE TITLE
Remember custom Yuzu folder

### ISSUE THREAD

**Issue by Supergamer1337** [vasilvestre/totk-mod-manager-for-switch-emulators#54]
**Is your feature request related to a problem? Please describe.**
Currently, everytime I open the mod manager it does not remeber my custom Yuzu user folder. It would be great not having to manually locate it everytime.

**Describe the solution you'd like**
Save it somewhere, maybe a json file alongside the application.

**Comment by vasilvestre** [comment]
Seems to be the issue here : https://github.com/tauri-apps/plugins-workspace/pull/32
Will ask for a merge or ultimately, use the fork.
