### ISSUE TITLE
Disable Dynamic Resolution (stand alone) missing?

### ISSUE THREAD

**Issue by KeithGS** [vasilvestre/totk-mod-manager-for-switch-emulators#57]
I cannot find DynRes just by itself anymore, only in packs..unless it's not required anymore?

Thanks.

**Comment by vasilvestre** [comment]
From holographics changelog at 2.0, dynres has been removed because it create bugs and it's useless with most recommended mods 
See https://github.com/HolographicWings/TOTK-Mods-collection/releases/tag/v2.0
