### ISSUE TITLE
[Bug]:  Missing , or : between flow map items at line 20, column 37: - { name: 'Fayaz', 'Fruithapje21' link: 'https://gamebanana.com/mods/updates/… ^

### ISSUE THREAD

**Issue by hoangkm13** [vasilvestre/totk-mod-manager-for-switch-emulators#59]
### Describe the bug

```bash
Missing , or : between flow map items at line 20, column 37: - { name: 'Fayaz', 'Fruithapje21' link: 'https://gamebanana.com/mods/updates/… ^
```

### Reproduction steps

```bash
Just open the app. Tried delete both inner cache and mod location config
```

### What's your operating system?

Windows 11

**Comment by AstraXIV** [comment]
Same issue, tried uninstalling and reinstalling as well. Also have no idea where it downloads the modpack to try and remove that file.

**Comment by Write** [comment]
We'll have to wait for an update, the other mod manager has the exact same issue too.

**Comment by vasilvestre** [comment]
The distant source newest 2.2 (I think) broke the yaml format. A release is to come, I think it's a weekly release so next week..

**Comment by JacobDrivers** [comment]
Same issues. Looks like an update is needed.

**Comment by JacobDrivers** [comment]
Update: It seems to work correctly now. I think it was an issue on HolographicWing's side indicated in their [patch notes](https://github.com/HolographicWings/TOTK-Mods-collection/releases/tag/v2.2.1).

"Changelog

v2.2.1

- Fixed several bugs that were breaking mod managers"

**Comment by vasilvestre** [comment]
It's been fixed and I've added a CI check to the Holographic's repo to ensure that all configuration are correct.
Thank you for the report, feels free to reopen if the issue come again :)
