### ISSUE TITLE
[Bug]: File or Folder does not exist

### ISSUE THREAD

**Issue by Krizwolfman** [vasilvestre/totk-mod-manager-for-switch-emulators#62]
### Describe the bug

```bash
Hi! Great Job!
First of all, THANKS for your work.
I've been using this Mod Manager for a couple weeks ow, but today it comes up with a warning that says:
"path: /home/USER/.local/share/com.vasilvestre.totkMM/v4.20/Mods: File or folder does not exist (os error 2)"
And, ehenever I open the game, graphics (Vulkan, cause' I'm playing on Intel UHD 630) appear glitched.
May you help me figure this out?
```

### Reproduction steps

```bash
Everything was ok, and then I tried to update Mesa drivers (genius), and now, the game comes up with some glitch. That's the only new thing I did.
At the title screen, I can see the menu text, and options, but the background is full of black triangles.
When I enter the game, Link, the npc and the landscape is full of black triangles, except the sky.
Thank you in advance for any advice.
```

### Additional context

```bash
1.
2.
3.
...
```

### What's your operating system?

Linux

**Comment by vasilvestre** [comment]
I think the last update of mod repository broke the  mod manager. They released a new tool which optimize and add some mod..
I will take a look, I can see a quick fix anyway!

**Comment by vasilvestre** [comment]
A new release will be made in some minutes, try it but it now works fine for me

**Comment by vasilvestre** [comment]
New release made, it works great for me ! Give it a try and reopen the issue if you encounter a similar issue

**Comment by Krizwolfman** [comment]
Good day! Thanks!
I'll give it a try.

Forgot to mention, I'm on Linux. So I will search for the .appimage version.

**Comment by vasilvestre** [comment]
> Good day! Thanks! I'll give it a try.
> 
> Forgot to mention, I'm on Linux. So I will search for the .appimage version.

They are all built automatically and released with the updater

**Comment by Krizwolfman** [comment]
Hi
It seems to be working now :D

Thanks!
